[package]
name = "gitguardian"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.39"
dotenvy = "0.15.7"
octocrab = "0.43.0"
rand = "0.8.5"
tokio = { version = "1.43", features = ["rt-multi-thread", "macros"] }
